#!/usr/bin/env python
# coding: utf-8

# In[1]:


pip install "notebook>=5.3" "ipywidgets>=7.5"


# In[4]:


print('ISS')


# In[2]:


import pandas as pd
import plotly.express as px


# In[3]:


url = 'http://api.open-notify.org/iss-now.json'


# In[8]:


fd = pd.read_json(url)


# In[6]:


fd


# In[9]:


fd['latitude'] = fd.loc['latitude','iss_position']
fd['longitude'] = fd.loc['longitude','iss_position']
fd.reset_index(inplace = True )


# In[10]:


fd


# In[13]:


fd = fd.drop(['index','message'], axis=1)


# In[14]:


fd


# In[15]:


fig = px.scatter_geo(fd, lat='latitude', lon='longitude')


# In[17]:


fig.show()


# In[ ]:




